gettingstarted/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

import hello.views

# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [	
    url(r'^$', hello.views.index, name='index'),
    url(r'^db', hello.views.db, name='db'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/newAccount
    url(r'newAccount/$', views.NewAccountView.as_view(), name='newAccount'),
    # ex: /polls/account/
    url(r'account/$', views.AccountView.as_view(), name='account'),

    url(r'payment/$', views.PaymentView.as_view(), name='payment'),
    url(r'receipt/$', views.ReceiptView.as_view(), name='receipt'),
    url(r'approval/$', views.ApprovalView.as_view(), name='approval'),
    url(r'done/$', views.DoneView.as_view(), name='done'),
    #url(r'account/$', views.AccountView.as_view(), name='account'),
    #url(r'account/$', views.AccountView.as_view(), name='account'),
    #url(r'account/$', views.AccountView.as_view(), name='account'),



    # ex: /polls/saveAction/
    url(r'saveAction/$', views.SaveAction, name='saveAction'),

    url(r'saveOption/$', views.SaveOption, name='saveOption'),

    #url(r'myAccount/$', views.AccountView.as_view(), name='myAccount'),

    # ex: /polls/userOption/
    url(r'userOption/$', views.UserOptionView.as_view(), name='userOption'),

]

account/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)

polls/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
    	now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class UserAction(models.Model):
    ip_address = models.CharField(max_length=100)
    action_date = models.DateTimeField()
    action_object = models.CharField(max_length=100)
    action = models.CharField(max_length=100)
    def __str__(self):
        return '%s %s %s %s' % (self.ip_address, self.action_date, self.action_object, self.action)

account/views.py
from django.shortcuts import render

# Create your views here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Greeting

import requests

# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    return render(request, 'index.html')


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, 'db.html', {'greetings': greetings})

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from datetime import datetime
from ipware.ip import get_ip

from .models import Choice, Question, UserAction


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Return the last five published questions (not including those set to be
		published in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class UserOptionView(generic.ListView):
	model = UserAction
	template_name = 'polls/userOption.html'

class NewAccountView(generic.ListView):
	model = UserAction
	template_name = 'polls/newAccount.html'

class AccountView(generic.ListView):
	model = UserAction	
	template_name = 'polls/account.html'

class PaymentView(generic.ListView):
	model = UserAction
	template_name = 'polls/payment.html'

class ReceiptView(generic.ListView):
	model = UserAction
	template_name = 'polls/receipt.html'

class ApprovalView(generic.ListView):
	model = UserAction
	template_name = 'polls/approval.html'

class DoneView(generic.ListView):
	model = UserAction
	template_name = 'polls/done.html'

def SaveAction(request):
	user_action = UserAction(ip_address = get_ip(request), action_date = datetime.now(), action_object = 'My Account button', action = 'button press') 	
 	user_action.save()
 	return HttpResponseRedirect(reverse('polls:newAccount'))


def SaveOption(request):
	user_action = UserAction(ip_address = get_ip(request), action_date = datetime.now(), action_object = request.POST['option'] + ' button', action = 'button press')
	user_action.save()
	return HttpResponseRedirect(reverse('polls:index'))

hello/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>HCI Experiment</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/examples/cover/cover.css" rel="stylesheet">
</head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <!-- <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><u>Human Computer Interaction Experiement</u></h3>
            </div>
          </div> -->

          <div class="inner cover">
            <h1 class="cover-heading">Thank you for participating in the study!</h1>
            <br/>
            <br/>
            <p class="lead" align="left">
              The study involves completing a task similar to what you would do in a commonly used website.<br/><br/>
              The task involves paying a false internet provider bill. You will use the website as if you were paying a real bill online but will not be asked to provide real information such as payment details. The task is not timed and typically takes about 5 minutes. <br/><br/>
              The purpose of the experiment is to test usability of a website and not to determine how smart or computer literate you are.  The purpose is to test how well the website functions from a design perspective.  There will be a questionnaire at the end of the experiment.  Actions performed on the website will be recorded as well as responses to the exit questionnaire.  <br/><br/>
              You have the right to withdrawal from the experiment at any time without penalty.  <br/><br/>
              The results from the study will be used in a report for a project at the University of Nebraska at Omaha.  Personal information about yourself and the data collected during the study will not be released.  The information collected will not include uniquely identifying information such as your name or email.  Your confidentiality during and after the experiment will be protected.  <br/><br/>
              Once you have read the description of the study and understand your rights as a participant, <u>click the button below to start</u>.

            </p>
            <br/>
            <br/>
            <p>
              <a class="btn btn-lg btn-primary" href="{% url 'polls:userOption' %}" role="button">Start the Experiment &raquo;</a>
            </p>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    
  </body>
</html>

polls/templates/polls/account.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Independent Cable - Experiment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>



<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Independent Cable</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="progress" id="progressDiv">
      <div
        id="progressBar"
        class="progress-bar progress-bar-success"
        role="progressbar" 
        aria-valuenow="0" 
        aria-valuemin="0" 
        aria-valuemax="100" 
        data-transitiongoal="100"
        style="width:90%">
      </div>
    </div>

  </div>
</div>

<div class="container well" align="center">
  <h3>Welcome to your account!</h3>

  <br/>

  <h4>Your current balance is <b>$49.99</b> is due today.</h4>
  <br/>
  <br/>
  <div class="row"> 
    <div class="col-xs-12" style="height:40px">
      <b>How much would you like to pay? </b>
      <input type="number" min="0" value="49.99" size="4"/>
      <a class="btn btn-primary" href="{% url 'polls:payment' %}" role="button">Continue</a>
      <a class="btn btn-default"
          role="button"
          data-target="#myModal"
          data-toggle="modal">Cancel</a>
    </div>
  </div>
</div>

<div class="container">    
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>            
        </div>
        <div class="modal-body">
          <p>Do you want to cancel your progress?</p>
        </div>
        <div class="modal-footer">
          <a class="btn btn-primary" role="button" data-dismiss="modal">No</a>
          <a class="btn btn-default" role="button" href="{% url 'polls:index' %}">Yes</a>
        </div>
      </div>      
    </div>
  </div>
</div>

<br/>
<br/>
<div class="container">
	<footer>
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p>&copy; Independent Cable, Inc. &middot; <a href="">Privacy</a> &middot; <a href="">Terms</a></p>
	</footer>
</div>


<script language="javascript">
  var progressBar = document.getElementById("progressBar");

    //move progress bar to 100%
    var width = 90;
    var id = setInterval(frame, 1);
    function frame() {
      if (width >= 100) {
        clearInterval(id);
        document.getElementById("progressDiv").style.display = "none";
      } else {
        width += 10;
        progressBar.style.width = width + '%';

        
        //progressBar.style.visibility = "hidden";
      }
    }
</script>

polls/templates/polls/approval.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Independent Cable - Experiment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Independent Cable</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>            
          </ul>
        </div>
    </nav>

    <div class="progress" id="progressDiv">
        <div
        id="progressBar"
        class="progress-bar progress-bar-success"
        role="progressbar" 
        aria-valuenow="0" 
        aria-valuemin="0" 
        aria-valuemax="100" 
        data-transitiongoal="100"
        style="width:90%">
        </div>
      </div>
    </div>

  </div>
</div>

<div class="container well" align="center">
  <h3>Your payment has been accepted!</h3>
  <a class="btn btn-primary" href="{% url 'polls:receipt' %}" role="button">Continue</a>
  <a class="btn btn-default"
      role="button"
      data-target="#myModal"
      data-toggle="modal">Cancel</a>
</div>

<div class="container">    
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>            
        </div>
        <div class="modal-body">
          <p>Do you want to cancel your progress?</p>
        </div>
        <div class="modal-footer">
          <a class="btn btn-primary" role="button" data-dismiss="modal">No</a>
          <a class="btn btn-default" role="button" href="{% url 'polls:index' %}">Yes</a>
        </div>
      </div>      
    </div>
  </div>
</div>

<br/>
<br/>
<div class="container">
	<footer>
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p>&copy; Independent Cable, Inc. &middot; <a href="">Privacy</a> &middot; <a href="">Terms</a></p>
	</footer>
</div>

<script language="javascript">
  var progressBar = document.getElementById("progressBar");

    //move progress bar to 100%
    var width = 90;
    var id = setInterval(frame, 1);
    function frame() {
      if (width >= 100) {
        clearInterval(id);
        document.getElementById("progressDiv").style.display = "none";
      } else {
        width += 10;
        progressBar.style.width = width + '%';

        
        //progressBar.style.visibility = "hidden";
      }
    }
</script>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Independent Cable - Experiment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="navbar-wrapper">
    <div class="container">

      <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Independent Cable</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </div>

  <hr class="featurette-divider">
  <div align="center" class="well container">

    <form action="{% url 'polls:saveAction' %}" method="post">
      {% csrf_token %}
      <div class="row">       
        <div class="col-xs-12 col-sm-6" style="height:85px">          
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Watch Shows Online</button>
        </div>        
        <div class="col-xs-12 col-sm-6" style="height:85px">          
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Shop Products</button>
        </div>
      </div><!-- /.row -->
      
      <div class="row">
        <div class="col-xs-12 col-sm-6" style="height:85px">          
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">TV Listings</button>
        </div>        
        <div class="col-xs-12 col-sm-6" style="height:85px">
          <input type="submit" value="My Account" class="btn btn-lg btn-primary"/>
        </div>
        
      </div><!-- /.row -->
    </form>
  </div>

  <div class="container">
    
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
      
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>            
          </div>
          <div class="modal-body">
            <p>This button will not lead you to paying a bill.  Try another.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
        
      </div>
    </div>

    <footer>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>&copy; Independent Cable, Inc. &middot; <a href="">Privacy</a> &middot; <a href="">Terms</a></p>
    </footer>
    
  </div>

</body>
</html>

polls/templates/polls/newAccount.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Independent Cable - Experiment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Independent Cable</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>            
          </ul>
        </div>
      </div>
    </nav>

  </div>
</div>

<form name="signUp" action="{% url 'polls:account' %}" method="post">
      {% csrf_token %}

	<div align="center" class="container well">
		<div align="center">
			<h2>No account detected!</h2>
		</div>
		<div align="center">
			<h3>You must register for a new account.</h3>
		</div>

		<div class="row"> 
		  <div class="col-xs-12" style="height:40px">
		  	<b>Username : </b>
		  	<input type="text" name="username" required="required">
		  </div>
		</div>
		<div class="row">
		  <div class="col-xs-12" style="height:40px">
		  	<b>Password : </b>
		  	<input type="password" name="password" required="required">
		  </div>
		</div>
		<div class="row">
			<div id="progressRow" style="display:none">
				<div class="col-xs-3">
					&nbsp;
				</div>
				
				<div class="col-xs-6" style="height:80px;">
					<b>Strengthening and securely saving your password</b>
			  	<div class="progress">
					  <div
					  	id="progressBar"
					    class="progress-bar progress-bar-success" 
					  	role="progressbar" 
					  	aria-valuenow="0" 
					  	aria-valuemin="0" 
					  	aria-valuemax="100" 
					  	data-transitiongoal="100"
					  	style="width: 0%">
					  </div>
					</div>			
				</div>
				<div class="col-xs-3">
					&nbsp;
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12" style="height:40px">
				<input id="submitButton" type="submit" value="Submit" class="btn btn-primary" style="display:none">

				<a id="continueButton"
					style="visibility:hidden"
					class="btn btn-primary" 
					href="{% url 'polls:account' %}" 
					role="button">Continue</a>
				<a id="fortifyButton" 
					class="btn btn-primary" 
					onclick="fortifyPassword()" 
					role="button">Sign up</a>
				<a class="btn btn-default"
					role="button"
					data-target="#myModal"
					data-toggle="modal">Cancel</a>
			</div>
		</div>
	</div>
</form>

<div class="container">    
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>            
        </div>
        <div class="modal-body">
          <p>Do you want to cancel your progress?</p>
        </div>
        <div class="modal-footer">
          <a class="btn btn-primary" role="button" data-dismiss="modal">No</a>
          <a class="btn btn-default" role="button" href="{% url 'polls:index' %}">Yes</a>
        </div>
      </div>      
    </div>
  </div>
</div>

<br/>
<br/>
<div class="container">
	<footer>
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p>&copy; Independent Cable, Inc. &middot; <a href="">Privacy</a> &middot; <a href="">Terms</a></p>
	</footer>
</div>

<script language="javascript">	
	function fortifyPassword() {
		
		if(validateForm()) {
			document.getElementById("fortifyButton").className += " disabled";
			document.getElementById("progressRow").style.display = "inline";

			progressBar = document.getElementById("progressBar");			

			//move progress bar to 100%
			var width = 0;
		  var id = setInterval(frame, 30);
		  function frame() {
		    if (width >= 100) {
		      clearInterval(id);
		      progressBar.innerHTML = 'Complete!';

		      //Change button to "continue"
				  document.getElementById("fortifyButton").style.display = "none";
				  document.getElementById("continueButton").style.visibility = "visible";
		    } else {
		      width++;
		      //progressBar.innerHTML = width + '%';
		      progressBar.style.width = width + '%';

		    }
		  }
		}
	}

	function validateForm() {
		var username = document.forms["signUp"]["username"].value;		
		var password = document.forms["signUp"]["password"].value;
		if(username == null || username == "" || password == null || password == "") {
			document.getElementById("submitButton").click();
			return false;
		}
		return true;
	}

</script>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/userOption.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<div class="container">

  <!-- Main component for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h2>Pick an Option</h2>
    <p>
      <br/><br/>
      This website gives you two options.  Would you like a faster loading website or a website that consumes less energy to run the servers.
    </p>

    <form action="{% url 'polls:saveOption' %}" method="post">
		{% csrf_token %}
		<p align="center">
			<input type="submit" value="Save Some Energy" name="option" id="option" class="btn btn-lg btn-primary"/>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="submit" value="Fast Please" name="option" id="option" class="btn btn-lg btn-primary"/>
		</p>
	</form>
  </div>

</div>